'use client';
import {useEffect,useState,useCallback} from 'react';
import ReviewsManager from './ReviewsManager';
import TrafficCharts from './TrafficCharts';
import {api} from '../../lib/api';
const menus=[['overview','대시보드','운영 현황과 예약 전환'],['reservations','예약 내역','검색 · 일정 · 상태 관리'],['traffic','유입·전환 분석','최초 · 2차 · 예약 유입'],['journeys','방문 경로','세션별 이동 기록'],['reviews','이용후기','작성 · 공개 · 게시물 관리'],['files','파일 관리','이미지 · 안내 자료'],['settings','연결 설정','GA4 · 서비스 정보']];
const notificationLabels={pending:'발송 대기',sending:'발송 요청 중',accepted:'솔라피 접수 완료',failed:'발송 요청 실패',unknown:'결과 확인 필요'};
const statuses=['접수대기','확정','이용완료','취소'];
const labels={direct:'직접 / 출처 미확인',naver:'네이버 검색',naver_blog:'네이버 블로그',naver_cafe:'네이버 카페',google:'구글',daum:'다음',instagram:'인스타그램',facebook:'페이스북',threads:'스레드',youtube:'유튜브',kakaotalk:'카카오톡',untracked:'수집 이전 예약'};
const source=s=>labels[s]||s||'수집 기록 없음';
const time=t=>t?new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const eventsLabel={visit:'방문 시작',page_view:'페이지 보기',section_view:'섹션 보기',reservation_start:'예약 입력 시작',reservation_submit:'예약 제출',reservation_complete:'예약 접수 완료',reservation_error:'예약 접수 오류',phone_click:'전화 클릭',navigation_click:'메뉴 이동',outbound_click:'외부 링크 클릭',scroll_depth:'스크롤 도달',engagement:'활성 체류 측정'};
const stages=[['first','1차 · 최초 유입'],['second','2차 유입'],['reservation','예약 시점 유입']];
function Journey({value}){return !value?<p className="hj-muted">유입 추적 도입 이전 예약으로 과거 유입 기록이 없습니다.</p>:<><div className="hj-touch-grid">{stages.map(([key,label])=>{const t=value[key]||(key==='reservation'?value.last:null);return <div className="hj-touch" key={key}><small>{label}</small><strong>{source(t?.source)}</strong><span>{t?.medium||'—'}</span><span>{t?.campaign?'캠페인: '+t.campaign:'캠페인 없음'}</span>{t?.content&&<span>소재: {t.content}</span>}{t?.adId&&<span>광고 ID: {t.adId}</span>}<span>{t?.path||'—'}</span>{t?.referrer&&<span className="hj-break">{t.referrer}</span>}<span>{time(t?.at)}</span></div>})}</div><div className="hj-path"><strong>전체 유입 이력</strong>{value.touches?.map((t,i)=><span key={i}>{i+1}. {source(t.source)} / {t.medium} · {time(t.at)}</span>)}</div><div className="hj-path"><strong>이동 경로</strong>{value.paths?.map((p,i)=><span key={i}>{p.path} <small>{time(p.at)}</small></span>)}</div></>}
function Empty({children='아직 수집된 데이터가 없습니다.'}){return <div className="hj-empty">{children}</div>}
function Table({headers,rows}){return <div className="hj-table-wrap"><table className="hj-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>}
function Pager({page,total,onChange}){const count=Math.max(1,Math.ceil(total/50));return <div className="hj-pager"><span>총 {total.toLocaleString()}건 · {page} / {count}페이지</span><button disabled={page<=1} onClick={()=>onChange(page-1)}>이전</button><button disabled={page>=count} onClick={()=>onChange(page+1)}>다음</button></div>}
export default function AdminPage(){
 const [sidebarOpen,setSidebarOpen]=useState(false);
 const [user,setUser]=useState(null),[sessionLoading,setSessionLoading]=useState(true),[menu,setMenu]=useState('overview'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[rows,setRows]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[analytics,setAnalytics]=useState(null),[ga,setGa]=useState(null),[visits,setVisits]=useState([]),[visitTotal,setVisitTotal]=useState(0),[visitPage,setVisitPage]=useState(1),[expanded,setExpanded]=useState(null),[files,setFiles]=useState([]),[settings,setSettings]=useState(null),[stage,setStage]=useState('reservation'),[deletion,setDeletion]=useState(null);
 useEffect(()=>{api('auth/session').then(r=>setUser(r.user)).catch(e=>setMessage(e.message)).finally(()=>setSessionLoading(false));const view=new URLSearchParams(location.search).get('view');if(menus.some(m=>m[0]===view))setMenu(view)},[]);
 const params=useCallback(()=>{const p=new URLSearchParams();if(from)p.set('from',from);if(to)p.set('to',to);return p},[from,to]);
 const load=useCallback(async()=>{if(!user)return;setBusy(true);setMessage('');try{const p=params();if(['overview','reservations'].includes(menu)){p.set('page',String(menu==='overview'?1:page));p.set('size',menu==='overview'?'5':'50');if(search)p.set('q',search);if(status)p.set('status',status);const r=await api('admin/reservations?'+p);setRows(r.rows);setTotal(r.total)}if(['overview','traffic','journeys'].includes(menu))setAnalytics(await api('admin/analytics?'+params()));if(menu==='journeys'){p.set('page',String(visitPage));const r=await api('admin/journeys?'+p);setVisits(r.rows);setVisitTotal(r.total)}if(menu==='files'){const r=await api('admin/media');setFiles(r.rows);setSettings(s=>({...s,storage:r.enabled}))}if(menu==='settings')setSettings(await api('admin/settings'))}catch(e){setMessage(e.message)}finally{setBusy(false)}},[user,menu,page,search,status,params,visitPage]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!user||!['overview','traffic'].includes(menu))return;let cancelled=false;setGa(null);api('admin/ga4?'+params()).then(data=>{if(!cancelled)setGa(data)}).catch(e=>{if(!cancelled)setGa({available:false,message:e.message})});return()=>{cancelled=true}},[user,menu,params]);
 async function login(e){e.preventDefault();setBusy(true);setMessage('');try{const r=await api('auth/login',{method:'POST',body:JSON.stringify({email,password})});setUser(r.user);setPassword('')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function logout(){try{await api('auth/logout',{method:'POST'});setUser(null);setRows([]);setVisits([]);setAnalytics(null);setSettings(null);setFiles([])}catch(e){setMessage(e.message)}}
 function choose(view){setSidebarOpen(false);setMenu(view);setPage(1);setVisitPage(1);setExpanded(null);setDeletion(null);history.replaceState(null,'','/admin?view='+view)}
 async function update(id,value){setBusy(true);try{await api('admin/reservations/'+id,{method:'PATCH',body:JSON.stringify({status:value})});setRows(list=>list.map(r=>r.id===id?{...r,status:value}:r))}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(){setBusy(true);try{await api('admin/'+deletion.type+'/'+encodeURIComponent(deletion.id),{method:'DELETE'});setDeletion(null);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function upload(e){e.preventDefault();const form=e.currentTarget;setBusy(true);try{await api('admin/media',{method:'POST',body:new FormData(form)});form.reset();await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function exportCsv(){setBusy(true);try{const all=[];let current=1;while(true){const p=params();p.set('page',String(current++));p.set('size','200');if(search)p.set('q',search);if(status)p.set('status',status);const r=await api('admin/reservations?'+p);all.push(...r.rows);if(all.length>=r.total||!r.rows.length)break}const header=['접수일(한국시간)','예약자','연락처','입차일','입차시간','출차일','출차시간','노선','여행지','차량번호','모델','인원','골프백','요청사항','상태','최초 출처','최초 매체','2차 출처','예약 출처','예약 매체','캠페인','이동 경로'];const values=all.map(r=>[new Date(r.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}),r.name,r.phone,r.in_date,r.in_time,r.out_date,r.out_time,r.route,r.dest,r.plate,r.car,r.people,r.golf,r.note,r.status,r.journey?.first?.source,r.journey?.first?.medium,r.journey?.second?.source,r.journey?.reservation?.source,r.journey?.reservation?.medium,r.journey?.reservation?.campaign,r.journey?.paths?.map(p=>p.path).join(' → ')]);const safe=v=>{const s=String(v??'');return /^[=+@\-\t\r]/.test(s)?"'"+s:s};const csv='\uFEFF'+[header,...values].map(line=>line.map(v=>'"'+safe(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='형제주차장-예약내역.csv';a.click();URL.revokeObjectURL(url)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const summary=analytics?.summary||{},events=analytics?.events||[];
 const cards=[['방문자',summary.visitors||0,'동일 브라우저 기준'],['방문 세션',summary.sessions||0,'30분 비활동 후 새 방문'],['예약 접수',summary.bookings||0,'선택 기간의 전체 예약'],['예약 완료 세션 비율',summary.sessions?((events.find(e=>e.name==='reservation_complete')?.sessions||0)/summary.sessions*100).toFixed(1)+'%':'—','완료 세션 / 방문 세션']];
 const stats=<div className="hj-stats">{cards.map(([name,count,note])=><article key={name}><span>{name}</span><strong>{count.toLocaleString()}</strong><small>{note}</small></article>)}</div>;
 const reservationTable=<Table headers={['예약자 / 접수일','이용 일정','차량 / 여행지','최초 유입','예약 유입','상태','상세']} rows={rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><span>{r.phone}</span><small>{time(r.created_at)}</small></td><td><span>입차 {r.in_date} {r.in_time}</span><span>출차 {r.out_date} {r.out_time}</span></td><td><strong>{r.plate} · {r.car}</strong><span>{r.route} / {r.dest}</span></td><td><span className="hj-source-pill">{source(r.journey?.first?.source||'untracked')}</span><small>{r.journey?.first?.medium}</small></td><td><span className="hj-source-pill">{source(r.journey?.reservation?.source||'untracked')}</span><small>{r.journey?.reservation?.campaign}</small></td><td><select disabled={busy} aria-label={r.name+' 예약 상태'} value={r.status||'접수대기'} onChange={e=>update(r.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><button onClick={()=>setExpanded(expanded===r.id?null:r.id)}>{expanded===r.id?'접기':'상세 보기'}</button></td></tr>)}/>;
 if(sessionLoading)return <main className="admin-page"><Empty>관리자 세션을 확인하고 있습니다…</Empty></main>;
 if(!user)return <main className="admin-page"><header className="admin-header"><a href="/">형제주차장 <small>HYEONGJE PARKING</small></a><a href="/">사이트로 돌아가기</a></header><div className="admin-content admin-content-login"><span className="eyebrow">ADMIN DASHBOARD</span><h1>예약 관리자</h1><form className="admin-login" onSubmit={login}><h2>관리자 로그인</h2><p>기존 형제주차장 관리자 계정으로 로그인하세요.</p><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="primary-button" disabled={busy}>{busy?'로그인 중…':'로그인'}</button>{message&&<p className="admin-message" role="alert">{message}</p>}</form></div></main>;
 return <main className="hj-admin">{sidebarOpen&&<div className="hj-mobile-overlay" onClick={()=>setSidebarOpen(false)}/>}<aside className={"hj-sidebar"+(sidebarOpen?" is-open":"")}><a className="hj-brand" href="/admin">형제주차장<small>GIMHAE AIRPORT · ADMIN</small></a><span className="hj-nav-label">운영 관리</span><nav aria-label="관리자 메뉴">{menus.map(([id,title,desc],i)=><button key={id} className={menu===id?'active':''} onClick={()=>choose(id)} aria-current={menu===id?'page':undefined}><svg className="hj-nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d={["M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z","M5 4h14v17H5z M9 2v4 M15 2v4 M8 10h8 M8 14h8 M8 18h5","M4 20V10 M10 20V4 M16 20v-7 M22 20H2","M4 5h6v6H4z M14 13h6v6h-6z M10 8h7v5","M3 5h7l2 3h9v12H3z","M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M19 5l-2 2 M7 17l-2 2"][Math.min(i,5)]}/></svg><span><strong>{title}</strong><small>{desc}</small></span></button>)}</nav><div className="hj-sidebar-bottom"><span>{user.email}</span><a href="/" target="_blank" rel="noopener noreferrer">홈페이지 열기 ↗</a><button onClick={logout}>로그아웃</button></div></aside><div className="hj-main"><header className="hj-topbar"><button className="hj-menu-toggle" aria-label="관리자 메뉴 열기" onClick={()=>setSidebarOpen(!sidebarOpen)}>☰</button><span>김해공항 형제주차장</span><span className="hj-live">관리자 전용</span></header><div className="hj-workspace"><div className="hj-title"><div><span className="eyebrow">PARKING OPERATIONS</span><h1>{menus.find(m=>m[0]===menu)?.[1]}</h1><p>{menus.find(m=>m[0]===menu)?.[2]}</p></div><button disabled={busy} onClick={load}>{busy?'불러오는 중…':'새로고침'}</button></div>{message&&<p className="hj-alert" role="alert">{message}</p>}{['overview','reservations','traffic','journeys'].includes(menu)&&<div className="hj-filters"><label>접수·방문 시작일<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);setVisitPage(1)}}/></label><label>종료일<input type="date" min={from} value={to} onChange={e=>{setTo(e.target.value);setPage(1);setVisitPage(1)}}/></label><button onClick={()=>{setFrom('');setTo('');setSearch('');setQuery('');setStatus('');setPage(1);setVisitPage(1)}}>전체 기간</button></div>}
 {menu==='overview'&&<>{stats}<TrafficCharts analytics={analytics} ga={ga}/><div className="hj-columns"><section className="hj-card"><h2>예약 상태</h2>{statuses.map((s,i)=><div className="hj-metric-row" key={s}><span className={'hj-badge status-'+i}>{s}</span><strong>{analytics?.statuses?.find(x=>x.status===s)?.count||0}건</strong></div>)}<button onClick={()=>choose('reservations')}>예약 내역 보기 →</button></section><section className="hj-card"><h2>방문부터 예약까지</h2>{['visit','reservation_start','reservation_submit','reservation_complete'].map(n=>{const count=n==='visit'?summary.sessions||0:events.find(e=>e.name===n)?.sessions||0;return <div className="hj-funnel" key={n}><div><span>{eventsLabel[n]}</span><strong>{count}세션</strong></div><div className="hj-bar"><i style={{width:Math.min(100,count/(summary.sessions||1)*100)+'%'}}/></div></div>})}<small className="hj-muted">각 단계를 수행한 세션 수입니다. 기존 예약은 소급 추적되지 않습니다.</small></section></div><section className="hj-card"><div className="hj-card-heading"><h2>최근 예약</h2><button onClick={()=>choose('reservations')}>전체 내역 →</button></div>{reservationTable}{!rows.length&&<Empty>예약 내역이 없습니다.</Empty>}</section></>}
 {menu==='reservations'&&<section className="hj-card"><div className="hj-card-heading"><h2>예약 내역 <small>{total}건</small></h2><button disabled={busy||!total} onClick={exportCsv}>전체 검색 결과 CSV</button></div><form className="hj-search" onSubmit={e=>{e.preventDefault();setSearch(query);setPage(1)}}><input aria-label="예약 검색" placeholder="이름 · 휴대폰 · 차량번호 · 여행지" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="상태 필터" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">모든 상태</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button>검색</button></form>{reservationTable}{!rows.length&&!busy&&<Empty>검색 조건에 맞는 예약이 없습니다.</Empty>}<Pager page={page} total={total} onChange={setPage}/></section>}
 {['overview','reservations'].includes(menu)&&rows.filter(r=>r.id===expanded).map(r=><section className="hj-card" key={r.id}><div className="hj-card-heading"><h2>{r.name}님의 예약 상세</h2><button className="hj-danger" onClick={()=>setDeletion({type:'reservations',id:r.id,name:r.name+'님의 예약'})}>예약 삭제</button></div><dl className="hj-details"><div><dt>탑승 인원</dt><dd>{r.people}명</dd></div><div><dt>골프백</dt><dd>{r.golf||0}개</dd></div><div><dt>예약 번호</dt><dd>{r.id}</dd></div><div><dt>요청사항</dt><dd>{r.note||'없음'}</dd></div></dl><h3>예약 알림톡</h3><p className="hj-muted">솔라피 접수 완료는 발송 요청이 접수된 상태입니다. 실제 수신 결과는 솔라피 발송 내역에서 확인할 수 있습니다.</p>{r.notifications?.length?<dl className="hj-details">{r.notifications.map(n=><div key={n.recipient_role}><dt>{n.recipient_role==="operator"?"운영자 · 010-2896-1999":"예약 신청자"}</dt><dd>{notificationLabels[n.status]||n.status}<small> · {time(n.updated_at)}{n.error_code?" · "+n.error_code:""}</small>{n.group_id&&<span className="hj-break">발송 그룹: {n.group_id}</span>}</dd></div>)}</dl>:<p className="hj-muted">알림톡 연결 이전 예약입니다.</p>}<h3>예약으로 이어진 유입</h3><Journey value={r.journey}/></section>)}
 {menu==='traffic'&&<>{stats}<TrafficCharts analytics={analytics} ga={ga}/><section className="hj-card"><h2>예약 유입 기여</h2><p className="hj-muted">최초 · 2차 · 예약 당시의 출처를 각각 비교합니다. 단계별 예약 수는 중복될 수 있습니다.</p><div className="hj-tabs">{stages.map(([id,title])=><button key={id} className={stage===id?'active':''} onClick={()=>setStage(id)}>{title}</button>)}</div><Table headers={['유입 출처','매체','캠페인','예약 접수','확정·이용완료']} rows={analytics?.conversions?.filter(x=>x.stage===stage).map((x,i)=><tr key={i}><td><strong>{source(x.source)}</strong></td><td>{x.medium||'—'}</td><td>{x.campaign||'—'}</td><td>{x.bookings}건</td><td>{x.confirmed}건</td></tr>)}/>{!analytics?.conversions?.length&&<Empty/>}</section><section className="hj-card"><h2>전체 방문 유입</h2><Table headers={['출처','매체','캠페인','Referrer','방문','방문자']} rows={analytics?.sources?.map((x,i)=><tr key={i}><td><strong>{source(x.source)}</strong></td><td>{x.medium}</td><td>{x.campaign||'—'}</td><td className="hj-break">{x.referrer||'없음'}</td><td>{x.visits}</td><td>{x.visitors}</td></tr>)}/>{!analytics?.sources?.length&&<Empty/>}</section><div className="hj-columns"><section className="hj-card"><h2>행동별 집계</h2>{events.map(e=><div className="hj-metric-row" key={e.name}><span>{eventsLabel[e.name]||e.name}</span><strong>{e.count}회 <small>· {e.sessions}세션</small></strong></div>)}{!events.length&&<Empty/>}</section><section className="hj-card"><h2>일별 방문</h2>{analytics?.daily?.map(d=><div className="hj-metric-row" key={d.date}><span>{d.date}</span><strong>{d.visits}회</strong></div>)}{!analytics?.daily?.length&&<Empty/>}</section></div><p className="hj-muted">자체 DB 관측값입니다. GA4는 쿠키·차단·세션 정의 차이로 수치가 다를 수 있습니다. 출처 미확인 방문을 광고로 추정하지 않습니다.</p></>}
 {menu==='journeys'&&<><section className="hj-card"><h2>페이지·섹션 이동</h2><Table headers={['페이지','섹션','조회','활성 체류','세션당 체류']} rows={analytics?.paths?.map((p,i)=><tr key={i}><td>{p.path}</td><td>{p.section||'페이지 전체'}</td><td>{p.views}회</td><td>{Math.round((p.active_ms||0)/1000)}초</td><td>{Math.round((p.active_ms||0)/1000/(p.sessions||1))}초</td></tr>)}/>{!analytics?.paths?.length&&<Empty/>}</section><section className="hj-card"><h2>방문 세션별 경로</h2><p className="hj-muted">동일 브라우저의 관측 기록입니다. 다른 기기나 쿠키 삭제 후 방문은 연결되지 않습니다.</p>{visits.map(v=><details className="hj-visit" key={v.id}><summary><span><strong>{source(v.source)}</strong><small>{v.medium} · {v.campaign||'캠페인 없음'}</small></span><span>{v.device==='mobile'?'모바일':'PC'} · {time(v.created_at)}</span><span>이동 기록 {v.events.length}개</span></summary><Journey value={v.journey}/><div className="hj-timeline">{v.events.map((e,i)=><div key={i}><small>{time(e.created_at)}</small><strong>{eventsLabel[e.name]||e.name}</strong><span>{e.path}{e.section?' · '+e.section:''}</span></div>)}</div></details>)}{!visits.length&&<Empty/>}<Pager page={visitPage} total={visitTotal} onChange={setVisitPage}/></section></>}
 {menu==='reviews'&&<ReviewsManager/>}
 {menu==='files'&&<section className="hj-card"><h2>파일 보관함</h2><p className="hj-muted">주차장 이미지와 안내 PDF를 보관합니다. 파일은 관리자 로그인 후 열 수 있습니다.</p>{settings?.storage?<form className="hj-upload" onSubmit={upload}><input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" required/><button disabled={busy}>파일 업로드</button><small>이미지 · PDF, 최대 4MB</small></form>:<p className="hj-alert">Cloudflare 계정에서 R2 활성화가 필요합니다.</p>}{files.map(f=><div className="hj-file" key={f.key}><a href={'/api/media/'+encodeURIComponent(f.key)} target="_blank" rel="noopener noreferrer">{f.name} ↗</a><span>{(f.size/1024).toFixed(0)} KB · {time(f.created_at)}</span><button className="hj-danger" onClick={()=>setDeletion({type:'media',id:f.key,name:f.name})}>삭제</button></div>)}{!files.length&&<Empty>보관된 파일이 없습니다.</Empty>}</section>}
 {menu==='settings'&&<><section className="hj-card"><h2>서비스 연결</h2><dl className="hj-settings"><div><dt>홈페이지</dt><dd>Vercel · www.hjairport.com</dd></div><div><dt>예약 DB · API</dt><dd>{settings?.backend||'연결 중'}</dd></div><div><dt>파일 저장소</dt><dd>{settings?.storage?'Cloudflare R2':'R2 활성화 대기'}</dd></div><div><dt>GA4 측정 ID</dt><dd>{settings?.settings?.ga4_measurement_id||'설정 대기'}</dd></div><div><dt>GA4 보고서</dt><dd>{settings?.settings?.ga4_property_id?<a href={'https://analytics.google.com/analytics/web/#/p'+settings.settings.ga4_property_id+'/reports/intelligenthome'} target="_blank" rel="noopener noreferrer">애널리틱스 열기 ↗</a>:'설정 대기'}</dd></div><div><dt>관리자 계정</dt><dd>{user.email}</dd></div></dl></section><section className="hj-card"><h2>예약 알림톡 연결</h2><dl className="hj-settings"><div><dt>발송 서비스</dt><dd>SOLAPI · {settings?.notifications?.enabled?"연결 설정 완료":"설정 대기"}</dd></div><div><dt>운영자 수신번호</dt><dd>{settings?.notifications?.operatorPhone||"설정 대기"}</dd></div><div><dt>신청자 템플릿</dt><dd>{settings?.notifications?.customerTemplate||"설정 대기"}</dd></div><div><dt>운영자 템플릿</dt><dd>{settings?.notifications?.operatorTemplate||"설정 대기"}</dd></div></dl>{!!settings?.notifications?.missing?.length&&<p className="hj-alert">필요한 서버 설정: {settings.notifications.missing.join(", ")}</p>}<p>예약 저장 후 신청자와 운영자에게 각각 요청합니다. API 키와 시크릿키는 Cloudflare Secret에 보관하며 화면에 표시하지 않습니다. 결과가 불명확한 요청은 중복 발송 방지를 위해 자동 재발송하지 않습니다.</p></section><section className="hj-card"><h2>추적 기준</h2><p>1차는 이 브라우저의 최초 유입, 2차는 그다음 유입, 예약 유입은 접수 당시의 출처입니다. 캠페인과 페이지·섹션 이동 기록을 함께 보관합니다.</p><p>방문·이벤트와 최초 유입은 최대 90일 보관합니다. 관리자 페이지와 이름·전화번호·차량번호·요청사항은 GA4에 보내지 않습니다.</p><h3>광고 링크 예시</h3><code className="hj-link-example">https://www.hjairport.com/?utm_source=instagram&amp;utm_medium=cpc&amp;utm_campaign=airport_parking&amp;utm_content=ad_01</code></section></>}
 </div></div>{deletion&&<div className="hj-modal-backdrop"><section className="hj-modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">삭제하시겠습니까?</h2><p>{deletion.name}</p><p className="hj-muted">삭제한 데이터는 관리자 화면에서 복원할 수 없습니다.</p><div><button disabled={busy} onClick={()=>setDeletion(null)}>취소</button><button className="hj-danger" disabled={busy} onClick={remove}>삭제</button></div></section></div>}</main>;
}

